### ISSUE TITLE
Potions...Everywhere!

### ISSUE THREAD

**Issue by cerealconjugo** [omega-mc/glimmering-potions#2]
I install the mod, i mostly every time i broke grass, or a Dirt block it gives me a potion from the mod, maybe an issue with the mod  "Biomes Youll Go"

**Comment by Draylar** [comment]
Can you send me a mod list? Right now, potions are added to any loot table that contains "dungeon," or "treasure," in their name.

**Comment by cerealconjugo** [comment]
Ohhh, that explains the problem! I have a mod called Java-Dungeons, it seems to only happens when im on a Biome called dungeon:creeper.forest (a custom biome from Java-Dungeons)

**Comment by Draylar** [comment]
Just pushed a fix in [1.1.1](https://github.com/Draylar/glimmering-potions/releases/tag/1.1.1-1.16.1), let me know if it resolves the issue.

**Comment by cerealconjugo** [comment]
Its seems to be unable to download the fix, error "Page not found" before try to download the mod version 1.1.1 on CurseForge
